name: mousqe_workspace
publish_to: none

environment:
  sdk: ^3.13.0

dev_dependencies:
  melos: ^8.0.0

workspace:
  - packages/mousqe_core
  - packages/mousqe_ui
  - apps/teacher

melos:
  name: mousqe

  packages:
    - apps/*
    - packages/*

  command:
    bootstrap:
      runPubGetInParallel: true

  scripts:
    analyze:
      run: melos exec -- flutter analyze
      description: تحليل ثابت لكل الحزم
    test:
      run: melos exec --dir-exists=test -- flutter test
      description: تشغيل اختبارات كل الحزم
    format:
      run: melos exec -- dart format .
    gen:
      run: melos exec --depends-on="build_runner" -- dart run build_runner build --delete-conflicting-outputs
      description: توليد freezed / drift / retrofit
